// "use client"

import Protected from "@/utils/Protected"
import Navbar from "../Components/Loader/Navbar/Navbar"

// import RequireAuth from "../lib/ReuquireAuth"

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <>
            <Navbar/>
            <Protected>
                {children}
            </Protected>
        </>
    )
}